[package]
name = "pgx-utils"
version = "0.1.21"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Utility functions for 'pgx'"
homepage = "https://github.com/zombodb/pgx/pg-utils"
repository = "https://github.com/zombodb/pgx/pg-utils"
documentation = "https://docs.rs/pgx-utils"
readme = "README.md"

[dependencies]
colored = "2.0.0"
dirs = "3.0.2"
env_proxy = "0.4.1"
proc-macro2 = "1.0.26"
quote = "1.0.9"
regex = "1.5.2"
rttp_client = "0.1.0"
serde = "1.0.125"
serde_derive = "1.0.125"
serde-xml-rs = "0.4.1"
serde_json = "1.0.64"
syn = { version = "1.0.71", features = [ "extra-traits", "full", "fold", "parsing", "printing" ] }
toml = "0.5.8"
unescape = "0.1.0"
url = "2.2.1"
inventory = "0.1.10"
once_cell = "1.7.2"
eyre = "0.6.5"
color-eyre = "0.5.11"
tracing = "0.1.26"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.18"
petgraph = "0.5.1"